'use client';

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Lang = 'pt' | 'en';

export const translations = {
  pt: {
    nav: {
      dashboard: 'Painel',
      sms: 'SMS',
      email: 'Email',
      whatsapp: 'WhatsApp',
      applications: 'Aplicações',
      wallet: 'Carteira',
      developer: 'Developer',
      settings: 'Definições',
      admin: 'Administração',
      usersApps: 'Utilizadores e Apps',
      adminUsers: 'Utilizadores',
      adminApps: 'Aplicações',
      earnings: 'Receitas',
      smsLogs: 'Registos SMS',
      logout: 'Sair',
      loggingOut: 'A sair...',
    },
    header: { live: 'Em Direto', offline: 'Offline' },
    dashboard: {
      title: 'Painel',
      quickActions: 'Ações Rápidas',
      sendSms: 'Enviar SMS',
      sendEmail: 'Enviar Email',
      sendWhatsApp: 'Enviar WhatsApp',
      topUpWallet: 'Carregar Carteira',
      getApiKeys: 'Obter Chaves API',
    },
    stats: {
      smsSentToday: 'SMS Enviados Hoje',
      emailsSentToday: 'Emails Enviados Hoje',
      whatsappToday: 'WhatsApp Hoje',
      walletBalance: 'Saldo da Carteira',
    },
    activity: {
      title: 'Mensagens Recentes',
      last10: 'Últimas 10 mensagens',
      channel: 'Canal',
      to: 'Para',
      message: 'Mensagem',
      status: 'Estado',
      cost: 'Custo',
      date: 'Data',
      noMessages: 'Sem mensagens',
      noMessagesDesc: 'As suas mensagens recentes aparecerão aqui quando começar a enviar.',
    },
    smsForm: {
      title: 'Enviar SMS',
      application: 'Aplicação',
      selectApplication: 'Selecionar aplicação',
      noApplications: 'Sem aplicações',
      to: 'Para (Número de Telefone)',
      message: 'Mensagem',
      chars: 'caract.',
      sms: 'SMS',
      willCost: 'Esta mensagem custará',
      segment: 'segmento SMS',
      segments: 'segmentos SMS',
      at: 'a',
      each: 'cada',
      sendButton: 'Enviar SMS',
    },
    applications: {
      title: 'Aplicações',
      newApplication: 'Nova Aplicação',
      createApplication: 'Criar Aplicação',
      noApps: 'Sem aplicações',
      noAppsDesc: 'Crie a sua primeira aplicação para começar a enviar mensagens e gerar chaves API.',
      active: 'Ativa',
      inactive: 'Inativa',
      pendingApproval: 'Aprovação pendente',
      approved: 'Aprovada',
      rejected: 'Rejeitada',
      awaitingApproval: 'A aguardar aprovação do administrador para enviar mensagens.',
      reason: 'Motivo:',
      appIdLabel: 'ID da Aplicação',
      copyId: 'Copiar ID',
      idCopied: 'ID copiado',
      messages: 'mensagens',
      created: 'Criado',
      edit: 'Editar',
    },
    wallet: {
      title: 'Carteira',
      availableMessages: 'Mensagens Disponíveis',
      balance: 'Saldo',
      topUp: 'Carregar',
      fundsUsed: 'O saldo é debitado automaticamente ao enviar mensagens',
      transactionHistory: 'Histórico de Transações',
      checkingPayments: 'A verificar...',
      refreshStatus: 'Atualizar estado',
      transactions: 'transações',
      date: 'Data',
      type: 'Tipo',
      description: 'Descrição',
      entityRef: 'Entidade / Referência',
      amount: 'Valor',
      status: 'Estado',
      noTransactions: 'Sem transações',
      noTransactionsDesc: 'Carregue a sua carteira para começar. As transações aparecerão aqui.',
    },
    notifications: {
      title: 'Notificações',
      markAllRead: 'Marcar todas como lidas',
      noNotifications: 'Sem notificações',
      noNotificationsDesc: 'As suas notificações aparecerão aqui.',
      viewWallet: 'Ver carteira',
    },
    developer: {
      title: 'Developer',
      apiKeys: 'Chaves API',
      keyCount: 'chave(s)',
      createNewKey: 'Criar Nova Chave',
      noApiKeys: 'Sem chaves API',
      noApiKeysDesc: 'Crie uma chave API para começar a integrar o StrongX nas suas aplicações.',
      createApiKey: 'Criar Chave API',
      tableKeyName: 'Nome',
      tableKeyPrefix: 'Prefixo',
      tableApplication: 'Aplicação',
      tableCreated: 'Criado',
      tableLastUsed: 'Último Uso',
      tableStatus: 'Estado',
      tableAction: 'Ação',
      activeStatus: 'Ativa',
      revokedStatus: 'Revogada',
      neverUsed: 'Nunca',
      revokeKeyTitle: 'Revogar Chave API',
      revokeKeyConfirm: 'Tem a certeza que quer revogar',
      revokeKeyWarning: 'Qualquer aplicação que use esta chave perderá acesso imediatamente.',
      cancelBtn: 'Cancelar',
      revokeBtn: 'Revogar Chave',
      revokeSuccess: 'Chave API revogada',
      revokeFailed: 'Erro ao revogar chave',
      createKeyTitle: 'Criar Chave API',
      keyCreatedTitle: 'Chave API Criada',
      saveKeyNow: 'Guarde esta chave agora',
      saveKeyWarning: 'Esta é a única vez que a chave completa será mostrada. Se a perder, terá de criar uma nova.',
      yourApiKey: 'A sua Chave API',
      keyNameLabel: 'Nome da Chave',
      keyNamePlaceholder: 'A minha chave de produção',
      keyNameHint: 'Um nome descritivo para identificar esta chave',
      appOptional: 'Aplicação (Opcional)',
      noSpecificApp: 'Sem aplicação específica',
      savedMyKey: 'Guardei a minha chave',
      keyCopied: 'Chave API copiada!',
      copyFailed: 'Erro ao copiar',
      createFailed: 'Erro ao criar chave',
    },
    bulk: {
      title: 'SMS em Massa',
      contactsFile: 'Ficheiro de Contactos',
      downloadTemplate: 'Descarregar modelo',
      dropHint: 'Arraste o seu .xlsx ou .csv aqui, ou clique para escolher',
      contactsLoaded: 'contactos carregados — clique para substituir',
      columnInfo: 'Coluna A: Número de telefone · Coluna B: Nome',
      contacts: 'contactos',
      failed: 'falharam',
      clear: 'Limpar',
      personalizeHint: 'Use {{nome}} para personalizar com o nome do contacto',
      sending: 'A enviar...',
      stopSending: 'Parar envio',
      sendTo: 'Enviar para',
      contact: 'contacto',
      contactPlural: 'contactos',
      selectApp: 'Selecione uma aplicação',
      enterMessage: 'Introduza uma mensagem',
      uploadFile: 'Carregue um ficheiro de contactos',
      noPending: 'Sem contactos pendentes para enviar',
      done: 'Concluído —',
      msgSent: 'mensagem(ns) enviada(s)',
      countLoaded: 'contactos carregados',
    },
    topUp: {
      title: 'Carregar Carteira',
      referenceCreated: 'Referência de Pagamento Criada',
      useAtm: 'Use os seguintes detalhes para pagar na caixa Multicaixa ou via app Multicaixa Express.',
      entity: 'Entidade',
      reference: 'Referência',
      amount: 'Valor',
      referenceValid: 'Referência válida por 48 horas. O saldo será atualizado automaticamente após o pagamento.',
      savedInHistory: 'Esta referência está guardada no histórico de transações e foi enviada para o seu email.',
      done: 'Concluído',
      amountAoa: 'Valor (AOA)',
      paymentMethod: 'Método de Pagamento',
      gpoDesc: 'Pagar via telefone',
      atmDesc: 'Pagar no ATM',
      multicaixaPhone: 'Telefone Multicaixa Express',
      willTopUp: 'Vai carregar',
      toWallet: 'na sua carteira',
      cancel: 'Cancelar',
      payWithGpo: 'Pagar com GPO',
      getReference: 'Obter Referência',
      paymentSuccess: 'Pagamento bem-sucedido!',
      walletCredited: 'A sua carteira foi carregada.',
      copied: 'Copiado!',
      copyFailed: 'Erro ao copiar',
    },
    email: { title: 'Email', comingSoon: 'Brevemente', comingSoonDesc: 'O envio de emails estará disponível em breve. Por enquanto, utilize o canal SMS para as suas campanhas de mensagens.' },
    whatsapp: { title: 'WhatsApp', comingSoon: 'Brevemente', comingSoonDesc: 'O canal WhatsApp estará disponível em breve. Por enquanto, utilize o canal SMS para as suas campanhas de mensagens.' },
    settings: {
      title: 'Definições',
      profile: 'Perfil',
      security: 'Segurança',
      notifications: 'Notificações',
      profileInfo: 'Informação do Perfil',
      fullName: 'Nome Completo',
      emailAddress: 'Endereço de Email',
      phoneNumber: 'Número de Telefone',
      emailCannotChange: 'O email não pode ser alterado. Contacte o suporte se necessário.',
      phoneCannotChange: 'O telefone não pode ser alterado. Contacte o suporte se necessário.',
      saveChanges: 'Guardar Alterações',
      changePassword: 'Alterar Password',
      currentPassword: 'Password Atual',
      newPassword: 'Nova Password',
      confirmNewPassword: 'Confirmar Nova Password',
      enterCurrentPassword: 'Introduza a password atual',
      enterNewPassword: 'Introduza a nova password',
      repeatNewPassword: 'Repita a nova password',
      updatePassword: 'Atualizar Password',
      notificationPrefs: 'Preferências de Notificação',
      emailOnDelivery: 'Email na entrega',
      emailOnDeliveryDesc: 'Receber um email quando uma mensagem é entregue',
      emailOnFailure: 'Email em caso de falha',
      emailOnFailureDesc: 'Receber um email quando uma mensagem falha',
      smsOnLowBalance: 'SMS com saldo baixo',
      smsOnLowBalanceDesc: 'Receber um SMS quando o saldo da carteira está baixo',
      weeklyReport: 'Relatório semanal',
      weeklyReportDesc: 'Receber um resumo semanal da utilização',
      lowBalanceThreshold: 'Limiar de Saldo Baixo (AOA)',
      savePreferences: 'Guardar Preferências',
      profileUpdated: 'Perfil atualizado com sucesso!',
      profileUpdateFailed: 'Erro ao atualizar perfil',
      passwordChanged: 'Password alterada com sucesso!',
      passwordChangeFailed: 'Erro ao alterar password',
      prefsSaved: 'Preferências guardadas!',
      prefsSaveFailed: 'Erro ao guardar preferências',
    },
    auth: {
      welcomeBack: 'Bem-vindo de volta',
      signInToAccount: 'Entre na sua conta',
      emailAddress: 'Endereço de Email',
      password: 'Password',
      forgotPassword: 'Esqueceu a password?',
      signIn: 'Entrar',
      noAccount: 'Não tem conta?',
      createAccount: 'Criar conta',
      createYourAccount: 'Crie a sua conta',
      startSending: 'Comece a enviar mensagens em minutos',
      fullName: 'Nome Completo',
      phone: 'Número de Telefone',
      phoneFormat: '(formato +244)',
      confirmPassword: 'Confirmar Password',
      createAccountBtn: 'Criar Conta',
      agreeTerms: 'Ao criar uma conta, concorda com os nossos',
      termsLink: 'Termos de Serviço',
      and: 'e',
      privacyLink: 'Política de Privacidade',
      alreadyAccount: 'Já tem conta?',
      passwordStrength: 'Robustez',
      strengthLabels: ['', 'Muito Fraca', 'Fraca', 'Razoável', 'Forte', 'Muito Forte'],
      verifyPhoneTitle: 'Verificar Telefone',
      verifyPhoneDesc: 'Enviámos um código OTP para',
      enterOtp: 'Introduza o código OTP de 6 dígitos enviado para o seu telefone',
      otpPlaceholder: '000000',
      verify: 'Verificar',
      didntReceive: 'Não recebeu o código?',
      resend: 'Reenviar',
      resending: 'A reenviar...',
      checkEmail: 'Verifique o seu Email',
      sentVerificationTo: 'Enviámos um link de verificação para',
      yourEmailAddress: 'o seu endereço de email',
      whatNext: 'O que fazer a seguir:',
      emailStep1: 'Abra a sua caixa de correio',
      emailStep2: 'Encontre o email da StrongX',
      emailStep3: 'Clique no botão "Verificar Email" no email',
      emailStep4: 'Será redirecionado para o login',
      didntReceiveEmail: 'Não recebeu o email?',
      resendVerification: 'Reenviar email de verificação',
      checkSpam: 'Verifique o spam. O link expira em 24 horas.',
      emailVerifiedSuccess: 'Email verificado com sucesso!',
      emailVerifiedDesc: 'A redirecionar para o login...',
      emailVerifiedFailed: 'Falha na verificação',
      verifyingEmail: 'A verificar o seu email...',
      forgotPasswordTitle: 'Esqueceu a Password?',
      forgotPasswordDesc: 'Introduza o seu email e enviaremos um link para redefinir a password.',
      sendResetLink: 'Enviar Link de Reset',
      resetLinkSent: 'Link enviado!',
      resetLinkSentDesc: 'Verifique o seu email com as instruções para redefinir a password.',
      backToLogin: 'Voltar ao login',
      resetPasswordTitle: 'Redefinir Password',
      resetPasswordDesc: 'Introduza a sua nova password abaixo.',
      newPassword: 'Nova Password',
      confirmPassword2: 'Confirmar Password',
      resetBtn: 'Redefinir Password',
      backToRegister: 'Voltar ao registo',
      yourPhoneNumber: 'o seu número de telefone',
      verifyPhoneBtn: 'Verificar Número de Telefone',
      resendCodeIn: 'Reenviar código em',
      resendCode: 'Reenviar código',
      sending: 'A enviar...',
      checkSms: 'Verifique a sua caixa de SMS. O código expira em 10 minutos.',
      ifAccountExists: 'Se existir uma conta para',
      resetLinkExpiry: 'receberá um link de reset. O link expira em 1 hora.',
      requestNewReset: 'Solicitar novo link de reset',
      invalidResetLink: 'Link de reset inválido',
      invalidResetDesc: 'Este link de reset de password é inválido ou expirou. Por favor solicite um novo.',
      setNewPassword: 'Definir nova password',
      chooseStrongPassword: 'Escolha uma password forte para a sua conta.',
      passwordResetSuccess: 'Password redefinida!',
      passwordResetSuccessDesc: 'A sua password foi redefinida com sucesso. Pode agora entrar com a nova password.',
      signInLink: 'Entrar',
      rememberPassword: 'Lembra-se da sua password? Entrar',
      enterPassword: 'Introduza a sua password',
      pleaseEnterOtp: 'Por favor introduza o código completo de 6 dígitos',
      phoneVerifiedToast: 'Telefone verificado!',
      phoneVerifiedDesc: 'Por favor verifique o seu email.',
      codeSent: 'Código enviado!',
      codeSentDesc: 'Um novo OTP foi enviado para o seu telefone.',
      resendFailed: 'Erro ao reenviar',
      loginFailed: 'Falha no Login',
      accountCreated: 'Conta criada!',
      accountCreatedDesc: 'Verifique o seu número de telefone para continuar.',
      registrationFailed: 'Falha no Registo',
      resetFailed: 'Falha no Reset',
      linkExpired: 'O link pode ter expirado. Solicite um novo abaixo.',
    },
  },
  en: {
    nav: {
      dashboard: 'Dashboard',
      sms: 'SMS',
      email: 'Email',
      whatsapp: 'WhatsApp',
      applications: 'Applications',
      wallet: 'Wallet',
      developer: 'Developer',
      settings: 'Settings',
      admin: 'Admin',
      usersApps: 'Users & Apps',
      adminUsers: 'Users',
      adminApps: 'Applications',
      earnings: 'Earnings',
      smsLogs: 'SMS Logs',
      logout: 'Logout',
      loggingOut: 'Logging out...',
    },
    header: { live: 'Live', offline: 'Offline' },
    dashboard: {
      title: 'Dashboard',
      quickActions: 'Quick Actions',
      sendSms: 'Send an SMS',
      sendEmail: 'Send an Email',
      sendWhatsApp: 'Send WhatsApp',
      topUpWallet: 'Top Up Wallet',
      getApiKeys: 'Get API Keys',
    },
    stats: {
      smsSentToday: 'SMS Sent Today',
      emailsSentToday: 'Emails Sent Today',
      whatsappToday: 'WhatsApp Today',
      walletBalance: 'Wallet Balance',
    },
    activity: {
      title: 'Recent Messages',
      last10: 'Last 10 messages',
      channel: 'Channel',
      to: 'To',
      message: 'Message',
      status: 'Status',
      cost: 'Cost',
      date: 'Date',
      noMessages: 'No messages yet',
      noMessagesDesc: 'Your recent messages will appear here once you start sending.',
    },
    smsForm: {
      title: 'Send SMS',
      application: 'Application',
      selectApplication: 'Select application',
      noApplications: 'No applications found',
      to: 'To (Phone Number)',
      message: 'Message',
      chars: 'chars',
      sms: 'SMS',
      willCost: 'This will cost',
      segment: 'SMS segment',
      segments: 'SMS segments',
      at: 'at',
      each: 'each',
      sendButton: 'Send SMS',
    },
    applications: {
      title: 'Applications',
      newApplication: 'New Application',
      createApplication: 'Create Application',
      noApps: 'No applications yet',
      noAppsDesc: 'Create your first application to start sending messages and generating API keys.',
      active: 'Active',
      inactive: 'Inactive',
      pendingApproval: 'Pending approval',
      approved: 'Approved',
      rejected: 'Rejected',
      awaitingApproval: 'Awaiting admin approval to send messages.',
      reason: 'Reason:',
      appIdLabel: 'Application ID',
      copyId: 'Copy ID',
      idCopied: 'Application ID copied',
      messages: 'messages',
      created: 'Created',
      edit: 'Edit',
    },
    wallet: {
      title: 'Wallet',
      availableMessages: 'Available Messages',
      balance: 'Balance',
      topUp: 'Top Up',
      fundsUsed: 'Funds are used automatically when sending messages',
      transactionHistory: 'Transaction History',
      checkingPayments: 'Checking...',
      refreshStatus: 'Refresh status',
      transactions: 'transactions',
      date: 'Date',
      type: 'Type',
      description: 'Description',
      entityRef: 'Entity / Reference',
      amount: 'Amount',
      status: 'Status',
      noTransactions: 'No transactions yet',
      noTransactionsDesc: 'Top up your wallet to get started. Your transactions will appear here.',
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all as read',
      noNotifications: 'No notifications',
      noNotificationsDesc: 'Your notifications will appear here.',
      viewWallet: 'View wallet',
    },
    developer: {
      title: 'Developer',
      apiKeys: 'API Keys',
      keyCount: 'key(s)',
      createNewKey: 'Create New Key',
      noApiKeys: 'No API keys',
      noApiKeysDesc: 'Create an API key to start integrating StrongX into your applications.',
      createApiKey: 'Create API Key',
      tableKeyName: 'Name',
      tableKeyPrefix: 'Key Prefix',
      tableApplication: 'Application',
      tableCreated: 'Created',
      tableLastUsed: 'Last Used',
      tableStatus: 'Status',
      tableAction: 'Action',
      activeStatus: 'Active',
      revokedStatus: 'Revoked',
      neverUsed: 'Never',
      revokeKeyTitle: 'Revoke API Key',
      revokeKeyConfirm: 'Are you sure you want to revoke',
      revokeKeyWarning: 'Any applications using this key will immediately lose access.',
      cancelBtn: 'Cancel',
      revokeBtn: 'Revoke Key',
      revokeSuccess: 'API key revoked',
      revokeFailed: 'Failed to revoke key',
      createKeyTitle: 'Create API Key',
      keyCreatedTitle: 'API Key Created',
      saveKeyNow: 'Save this key now',
      saveKeyWarning: 'This is the only time the full key will be shown. If you lose it, you\'ll need to create a new one.',
      yourApiKey: 'Your API Key',
      keyNameLabel: 'Key Name',
      keyNamePlaceholder: 'My production key',
      keyNameHint: 'A descriptive name to identify this key',
      appOptional: 'Application (Optional)',
      noSpecificApp: 'No specific application',
      savedMyKey: 'I\'ve saved my key',
      keyCopied: 'API key copied to clipboard!',
      copyFailed: 'Failed to copy',
      createFailed: 'Failed to create key',
    },
    bulk: {
      title: 'Bulk SMS',
      contactsFile: 'Contacts file',
      downloadTemplate: 'Download template',
      dropHint: 'Drop your .xlsx or .csv here, or click to browse',
      contactsLoaded: 'contacts loaded — click to replace',
      columnInfo: 'Column A: Phone number · Column B: Name',
      contacts: 'contacts',
      failed: 'failed',
      clear: 'Clear',
      personalizeHint: 'Use {{name}} to personalise with the contact\'s name',
      sending: 'Sending...',
      stopSending: 'Stop sending',
      sendTo: 'Send to',
      contact: 'contact',
      contactPlural: 'contacts',
      selectApp: 'Select an application',
      enterMessage: 'Enter a message',
      uploadFile: 'Upload a contacts file',
      noPending: 'No pending contacts to send to',
      done: 'Done —',
      msgSent: 'message(s) sent',
      countLoaded: 'contacts loaded',
    },
    topUp: {
      title: 'Top Up Wallet',
      referenceCreated: 'Payment Reference Created',
      useAtm: 'Use the following details to pay at any Multicaixa ATM or via the Multicaixa Express app.',
      entity: 'Entity',
      reference: 'Reference',
      amount: 'Amount',
      referenceValid: 'Reference valid for 48 hours. Your wallet will be updated automatically after payment.',
      savedInHistory: 'This reference is also saved in your transaction history and was emailed to you.',
      done: 'Done',
      amountAoa: 'Amount (AOA)',
      paymentMethod: 'Payment Method',
      gpoDesc: 'Pay via phone',
      atmDesc: 'Pay at ATM',
      multicaixaPhone: 'Multicaixa Express Phone',
      willTopUp: 'You will top up',
      toWallet: 'to your wallet',
      cancel: 'Cancel',
      payWithGpo: 'Pay with GPO',
      getReference: 'Get Reference',
      paymentSuccess: 'Payment successful!',
      walletCredited: 'Your wallet has been credited.',
      copied: 'Copied!',
      copyFailed: 'Failed to copy',
    },
    email: { title: 'Email', comingSoon: 'Coming Soon', comingSoonDesc: 'Email sending will be available soon. In the meantime, use the SMS channel for your messaging campaigns.' },
    whatsapp: { title: 'WhatsApp', comingSoon: 'Coming Soon', comingSoonDesc: 'The WhatsApp channel will be available soon. In the meantime, use the SMS channel for your messaging campaigns.' },
    settings: {
      title: 'Settings',
      profile: 'Profile',
      security: 'Security',
      notifications: 'Notifications',
      profileInfo: 'Profile Information',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      emailCannotChange: 'Email cannot be changed. Contact support if needed.',
      phoneCannotChange: 'Phone cannot be changed. Contact support if needed.',
      saveChanges: 'Save Changes',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      enterCurrentPassword: 'Enter current password',
      enterNewPassword: 'Enter new password',
      repeatNewPassword: 'Repeat new password',
      updatePassword: 'Update Password',
      notificationPrefs: 'Notification Preferences',
      emailOnDelivery: 'Email on delivery',
      emailOnDeliveryDesc: 'Receive an email when a message is delivered',
      emailOnFailure: 'Email on failure',
      emailOnFailureDesc: 'Receive an email when a message fails to deliver',
      smsOnLowBalance: 'SMS on low balance',
      smsOnLowBalanceDesc: 'Get an SMS when your wallet balance is low',
      weeklyReport: 'Weekly report',
      weeklyReportDesc: 'Receive a weekly summary of your usage',
      lowBalanceThreshold: 'Low Balance Threshold (AOA)',
      savePreferences: 'Save Preferences',
      profileUpdated: 'Profile updated successfully!',
      profileUpdateFailed: 'Failed to update profile',
      passwordChanged: 'Password changed successfully!',
      passwordChangeFailed: 'Failed to change password',
      prefsSaved: 'Notification preferences saved!',
      prefsSaveFailed: 'Failed to save preferences',
    },
    auth: {
      welcomeBack: 'Welcome back',
      signInToAccount: 'Sign in to your account',
      emailAddress: 'Email address',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      signIn: 'Sign In',
      noAccount: "Don't have an account?",
      createAccount: 'Create account',
      createYourAccount: 'Create your account',
      startSending: 'Start sending messages in minutes',
      fullName: 'Full Name',
      phone: 'Phone number',
      phoneFormat: '(+244 format)',
      confirmPassword: 'Confirm Password',
      createAccountBtn: 'Create Account',
      agreeTerms: 'By creating an account, you agree to our',
      termsLink: 'Terms of Service',
      and: 'and',
      privacyLink: 'Privacy Policy',
      alreadyAccount: 'Already have an account?',
      passwordStrength: 'Strength',
      strengthLabels: ['', 'Very Weak', 'Weak', 'Fair', 'Strong', 'Very Strong'],
      verifyPhoneTitle: 'Verify Your Phone',
      verifyPhoneDesc: 'We sent an OTP code to',
      enterOtp: 'Enter the 6-digit OTP code sent to your phone',
      otpPlaceholder: '000000',
      verify: 'Verify',
      didntReceive: "Didn't receive the code?",
      resend: 'Resend',
      resending: 'Resending...',
      checkEmail: 'Check your email',
      sentVerificationTo: "We've sent a verification link to",
      yourEmailAddress: 'your email address',
      whatNext: 'What to do next:',
      emailStep1: 'Open your email inbox',
      emailStep2: 'Find the email from StrongX',
      emailStep3: 'Click the "Verify Email" button in the email',
      emailStep4: "You'll be redirected to login",
      didntReceiveEmail: "Didn't receive the email?",
      resendVerification: 'Resend verification email',
      checkSpam: "Check your spam folder if you don't see it. The link expires in 24 hours.",
      emailVerifiedSuccess: 'Email verified successfully!',
      emailVerifiedDesc: 'Redirecting to login...',
      emailVerifiedFailed: 'Verification failed',
      verifyingEmail: 'Verifying your email...',
      forgotPasswordTitle: 'Forgot Password?',
      forgotPasswordDesc: "Enter your email and we'll send you a link to reset your password.",
      sendResetLink: 'Send Reset Link',
      resetLinkSent: 'Link sent!',
      resetLinkSentDesc: 'Check your email for instructions to reset your password.',
      backToLogin: 'Back to login',
      resetPasswordTitle: 'Reset Password',
      resetPasswordDesc: 'Enter your new password below.',
      newPassword: 'New Password',
      confirmPassword2: 'Confirm Password',
      resetBtn: 'Reset Password',
      backToRegister: 'Back to register',
      yourPhoneNumber: 'your phone number',
      verifyPhoneBtn: 'Verify Phone Number',
      resendCodeIn: 'Resend code in',
      resendCode: 'Resend code',
      sending: 'Sending...',
      checkSms: 'Check your SMS inbox. The code expires in 10 minutes.',
      ifAccountExists: 'If an account exists for',
      resetLinkExpiry: 'you will receive a password reset link. The link expires in 1 hour.',
      requestNewReset: 'Request new reset link',
      invalidResetLink: 'Invalid reset link',
      invalidResetDesc: 'This password reset link is invalid or has expired. Please request a new one.',
      setNewPassword: 'Set new password',
      chooseStrongPassword: 'Choose a strong password for your account.',
      passwordResetSuccess: 'Password reset!',
      passwordResetSuccessDesc: 'Your password has been reset successfully. You can now sign in with your new password.',
      signInLink: 'Sign in',
      rememberPassword: 'Remember your password? Sign in',
      enterPassword: 'Enter your password',
      pleaseEnterOtp: 'Please enter the complete 6-digit code',
      phoneVerifiedToast: 'Phone verified!',
      phoneVerifiedDesc: 'Now please verify your email address.',
      codeSent: 'Code sent!',
      codeSentDesc: 'A new OTP has been sent to your phone.',
      resendFailed: 'Failed to resend',
      loginFailed: 'Login Failed',
      accountCreated: 'Account created!',
      accountCreatedDesc: 'Please verify your phone number to continue.',
      registrationFailed: 'Registration Failed',
      resetFailed: 'Reset Failed',
      linkExpired: 'The link may have expired. Request a new one below.',
    },
  },
};

export type Translations = typeof translations.en;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextValue>({
  lang: 'pt',
  setLang: () => {},
  t: translations.pt,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('pt');

  useEffect(() => {
    const saved = localStorage.getItem('strongx_lang') as Lang | null;
    if (saved === 'pt' || saved === 'en') setLangState(saved);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('strongx_lang', l);
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

export function LangToggle() {
  const { lang, setLang } = useLang();
  return (
    <div className="flex items-center gap-0.5 border border-gray-200 rounded-lg p-0.5">
      {(['pt', 'en'] as Lang[]).map((l) => (
        <button
          key={l}
          onClick={() => setLang(l)}
          className={`px-2 py-0.5 rounded text-xs font-bold uppercase transition-colors ${
            lang === l ? 'bg-slate-700 text-white' : 'text-gray-400 hover:text-gray-700'
          }`}
        >
          {l}
        </button>
      ))}
    </div>
  );
}
